server.port=8088
server.servlet.context-path=/ChineseChess
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/openclaw_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=polk098

# Admin Configuration
security.admin.username=admin
security.admin.password=admin
